# Generated by Django 5.2.4 on 2025-07-08 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(110)])),
                ('global_score', models.IntegerField(default=0)),
                ('tournament_score', models.IntegerField(default=0)),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
